language: c
compiler:
  - clang
  - gcc
os:
 - linux
 - osx
before_install:
 - if [ "$TRAVIS_OS_NAME" != "linux" ]; then
     brew update;
     brew uninstall libzip;
     brew install libzip;
   else
     sudo apt-get -qq update;
     sudo apt-get install -y libxml2-dev libzip-dev libsqlite3-0;
   fi
script:
 - autoreconf -fiv
 - ./configure
 - make
 - make check
