language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Y2gkWJywGQ/p3Z2P5hzetXFq2CUX1WvwbHxBp3KUenYIwcJnue34eJL4thSbgqP040rmxT/dMC6sKwp1CykcSDS3CPeN1oI8SmwsCnCLrdoVOorv7Civb+hibV/vt5YAS7fckKKBZLNk1UnTRbX/Ls2vIn94ESsfRPPGCcgLY1sD7zL7KnSAGBla7OmZjNRYoRgSFlSf8SQCGDeBRi262FWXte4c0XNqHFzSUW1dfGayClJnju8vUz2dyvqR7JchyWaPINT/eE7Opfq4EjPiINwqdesF27B/uX5D2nofbjZjgmFrgvSZQuKOoTzeA5JCwB+VoGngd8NLeCh6sx5CDgzIraNjyqWbuWxIqkVTDCDTCbEVSN0mUMecUHlBipOVF+DIIhJ26ALVwbs3NtHGZY7EN2daoMJgFRhqsjRSYCO4NA4OjwB/frgRs5pLZLmbr2lCRtZf6mqYRaQTQycL+vtaqZea4xZUlhQd9CyiST9eMj1JC+li3f+2YegJX0/vxXlf7fbtXtdr4IPuIKG8BU1Qpx9bqJKddxsKvScX+jlH+2SUdlvDTDC2YnX6paqt4RBu6qwkHrRqgFdTYGhfvTeRIs+WNnHE9n4COniKDvrxfND+cXpIbmwZWencuuCnNJ5EiIiGmOTv0jYT7+xChfA2OVIxuBhRDSd/NGnICdo="

compiler:
  - clang
  - gcc
os:
 - linux
 - osx

addons:
  coverity_scan:
    project:
      name: "nih-at/ckmame"
      description: "Check ROM sets and dat files for MAME and other emulators"
    notification_email: dillo@nih.at,tk@giga.or.at
    build_command_prepend: "autoreconf -fiv; ./configure"
    build_command:   "make"
    branch_pattern: coverity_scan

before_install:
 - if [ "$TRAVIS_OS_NAME" != "linux" ]; then
     brew update;
     brew uninstall libzip;
     brew install libzip;
   else
     sudo apt-get -qq update;
     sudo apt-get install -y libxml2-dev libsqlite3-0 wget;
     for pkg in libzip4_1.1.2-1.1_amd64.deb libzip-dev_1.1.2-1.1_amd64.deb zipcmp_1.1.2-1.1_amd64.deb;
     do
       wget http://ubuntu.mirrors.tds.net/ubuntu/pool/universe/libz/libzip/$pkg;
       sudo dpkg -i $pkg;
     done
   fi
script:
 - autoreconf -fiv
 - ./configure
 - make
 - VERBOSE=yes make check
notifications:
  email:
    recipients:
      - dillo@nih.at,tk@giga.or.at
    on_success: change
    on_failure: change
